# Generated by Django 4.2.2 on 2023-11-19 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_user_profile_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 15, 40, 45, 748981)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='UyM3iHP6HQ77sDQSGx6dqc2-Zf4dsni56VNLKVcNVok', max_length=200),
        ),
    ]
