# Generated by Django 4.2.2 on 2023-11-19 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 15, 55, 53, 740831)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='WRixxlQ6oG0-iitE0lkybE-ZoKYBW8O2m6eV7ZWBo0k', max_length=200),
        ),
    ]
