# Generated by Django 4.2.2 on 2023-11-19 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_appointment_time_appointment_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 15, 59, 21, 231520)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.CharField(default='D0sPZWC7s2h_Y7xb_zeVv8Em7M2o8-Xw7ym_2hlh8ig', max_length=200),
        ),
    ]
